import type { Metadata } from "next";
import "../globals.css";
import { kanit } from "../fonts";
import AppHeader from "@/components/app/AppHeader";

export const metadata: Metadata = {
  title: "Junior App",
  description: "Generated by Junior",
};

export default function FrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable}`}>
        <AppHeader />
        {children}
      </body>
    </html>
  );
} 
